version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxyserver
    restart: unless-stopped
    ports:
      - 8081:80
      - 443:443
     volumes:
       - ./config:/etc/nginx/
       - ./static:/var/www/html
networks:
  default:
    external:
      name: avo4camerun-network
